##
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
##
mesosMaster: zk://20.26.28.244:2181,20.26.28.245:2181,20.26.28.246:2181/mesos
checkpoint: false
frameworkFailoverTimeout: 2000
frameworkName: Myriad2.0_CDH
frameworkRole: 
frameworkUser: root     # User the Node Manager runs as, required if nodeManagerURI set, otherwise defaults to the user
                          # running the resource manager.
frameworkSuperUser: root  # To be depricated, currently permissions need set by a superuser due to Mesos-1790.  Must be
                          # root or have passwordless sudo. Required if nodeManagerURI set, ignored otherwise.
nativeLibrary: /usr/local/lib/libmesos.so
zkServers: 20.26.28.244:2181,20.26.28.245:2181,20.26.28.246:2181
zkTimeout: 20000
restApiPort: 8192
profiles:
  zero:  # NMs launched with this profile dynamically obtain cpu/mem from Mesos
    cpu: 0
    mem: 0
  small:
    cpu: 1 
    mem: 1024
  medium:
    cpu: 2
    mem: 2048
  large:
    cpu: 4
    mem: 4096
nmInstances: # NMs to start with. Requires at least 1 NM with a non-zero profile.
  medium: 1 # <profile_name : instances>
rebalancer: false
haEnabled: true
nodemanager:
  jvmMaxMemoryMB: 1024
  cpus: 0.2
  cgroups: false
executor:
  jvmMaxMemoryMB: 256
  #path: file:///usr/local/libexec/mesos/myriad-executor-runnable-0.1.0.jar
  #The following should be used for a remotely distributed URI, hdfs assumed but other URI types valid.
  nodeManagerUri: hdfs://cluster/dist/config2.6.0.tgz
  path: hdfs://cluster/dist/hadoop-2.6.0.tar.gz
  #nodeManagerUri: hdfs://20.26.4.42:9000/dist/hadoop-myriad.tgz
  #path: hdfs://20.26.4.42:9000/dist/myriad-executor-runnable-0.1.0.jar
yarnEnvironment:
  YARN_HOME: /usr/hadoop-2.6.0-cdh5.8.3
  #YARN_HOME: hadoop-2.6.0-cdh5.8.3 #this should be relative if nodeManagerUri is set
  JAVA_HOME: /usr/local/jdk1.7.0 #System dependent, but sometimes necessary
mesosAuthenticationPrincipal:
mesosAuthenticationSecretFilename:
